apt-run: &ref_0
  name: Install Linux dependecies via apt.
  command: |
    apt-get update
    apt-get -y install meson desktop-file-utils appstream-util libglib2.0-bin
    gettext python3 libgee-0.8-dev libglib2.0-dev libgtk-3-dev valac
version: 2
jobs:
  build_eos_stable:
    docker:
      - image: 'elementary/docker:loki'
    steps:
      - checkout
      - run: *ref_0
      - run:
          name: Make build directory.
          command: mkdir build
      - run:
          name: Build with meson + ninja.
          command: meson build && ninja -C build
  build_eos_unstable:
    docker:
      - image: 'elementary/docker:loki-unstable'
    steps:
      - checkout
      - run: *ref_0
      - run:
          name: Make build directory.
          command: mkdir build
      - run:
          name: Build with meson + ninja.
          command: meson build && ninja -C build
  test_eos_stable:
    docker:
      - image: 'elementary/docker:loki'
    steps:
      - checkout
      - run: *ref_0
      - run:
          name: Make build directory.
          command: mkdir build
      - run:
          name: Build with meson + ninja.
          command: meson build && ninja -C build test
      - store_artifacts:
          path: build/meson-logs/testlog.txt
  test_eos_unstable:
    docker:
      - image: 'elementary/docker:loki-unstable'
    steps:
      - checkout
      - run: *ref_0
      - run:
          name: Make build directory.
          command: mkdir build
      - run:
          name: Build with meson + ninja.
          command: meson build && ninja -C build test
      - store_artifacts:
          path: build/meson-logs/testlog.txt
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_eos_stable
      - test_eos_stable
      - build_eos_unstable
      - test_eos_unstable
